image: centigrade/gitlab-ci-node-angular:10.16

stages:
  - install
  - build
  - test
  - deploy

# By default try fetching node_module in this pipeline
cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
    policy: pull

before_script:
  # Install dependencies if not fetched from cache
  - if [ ! -d "node_modules/" ]; then npm ci; fi
  - npm run cy:verify

install:dependencies:
  stage: install
  cache:
    key: ${CI_COMMIT_SHA}
    paths:
      - node_modules/
    # Always push new node_modules to cache
    policy: push
  script:
    - node -v
    - npm -v
    - pwd

build:production:
  stage: build
  script:
    - npm run build:prod:ci
  artifacts:
    paths:
      - ./dist
    expire_in: '2 hrs'

e2e:
  stage: test
  script:
    - npm run e2e:ci
  artifacts:
    paths:
      - cypress/screenshots
      - cypress/videos
    expire_in: '24 hrs'

pages:
  stage: deploy
  cache: {}
  before_script:
    - pwd
  script:
    - mkdir .public
    - cp -r dist/plastic-free/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  dependencies:
    - build:production
