# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-13 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name der Verpackung', max_length=255, unique=True)),
                ('amount', models.PositiveSmallIntegerField(help_text='Menge an Plastik in der Verpackung (Gramm)')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePackageAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(help_text='Menge an Verpackungen von diesem Typ')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.PackageType')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.Purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='packages',
            field=models.ManyToManyField(through='groceries.PurchasePackageAmount', to='groceries.PackageType'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='purchasepackageamount',
            unique_together=set([('package_type', 'purchase')]),
        ),
    ]
