# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-13 09:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(help_text='Einstufung des Nutzers')),
                ('family_size', models.SmallIntegerField(help_text='Anzahl Personen im Haushalt')),
                ('user', models.OneToOneField(help_text='Profil des Nutzers', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
