# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-13 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family_size',
            field=models.SmallIntegerField(default=1, help_text='Anzahl Personen im Haushalt'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.SmallIntegerField(choices=[(45000, 'beginner'), (37000, 'moderate'), (28000, 'hardliner')], default=37000, help_text='Einstufung des Nutzers'),
        ),
    ]
